spring:
  datasource:
    url: jdbc:h2:mem:lab2
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  flyway:
    enabled: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      url: jdbc:h2:mem:lab2
      driverClassName: org.h2.Driver
      username: sa
      password:
  logging:
    level:
      root: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: DEBUG
    pattern: "%-5level [%d{ISO8601}] [%thread] %logger{35} - %msg%n"


server:
  port: 8081